# Generated by Django 4.2.3 on 2023-07-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0004_alter_task_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-created_at']},
        ),
    ]
