# Generated by Django 4.2.3 on 2023-07-20 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("list_app", "0005_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="done",
            new_name="is_done",
        ),
    ]
